apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8000"

spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - port: {{ .Values.ports.port }}
    targetPort: {{ .Values.ports.targetPort}}
